# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

defaultContentLanguage:
  code: ko
defaultContentLanguageInSubdir:
  enabled: true

languages:
  ko:
    languageCode: ko-kr
    contentDir: content/ko
    languageName: 한국어
    weight: 1
  en:
    contentDir: content/en
    languageCode: en-us
    languageName: English
    weight: 2

  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en
# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
