# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: information
    url: tour
    weight: 10

  - name: introduce
    url: people
    weight: 20

  - name: CSAI(JBNU)
    url: event
    weight: 30

  - name: Project
    url: resume
    weight: 40
    hasChildren: true

  - name: interest
    weight: 50
    hasChildren: true
  - parent: interest
    name: 유튜브
    url: youtube
  - parent: interest
    name: IT, 뉴스레터
    url: itnews

  - name: contact
    url: contact
    weight: 60
